# Generated by Django 5.2 on 2026-04-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0002_financialrecord_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Summary',
                'verbose_name_plural': 'Dashboard Summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('records.financialrecord',),
        ),
    ]
