# Generated by Django 5.2 on 2026-04-05 05:45

import django.core.validators
import records.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_financialrecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(db_index=True, validators=[records.models.validate_past_or_today]),
        ),
    ]
